# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Sunghyun Chung
description: PhD MPH BSPH
baseurl: "/bay"
url: "https://eliottvincent.github.io"
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header: Sunghyun (Danny) Chung
  pages:
    - name: Home
      slug: /
    - name: Research
    - name: Teaching
    - name: Grants/Fundings
    - name: Talks
    - name: Blog

footer:
  show_powered_by: true
  contact:
    - type: email
      name: Email
      value: sunghyun@tamu.edu
  follow:
    - type: linkedin
      name: LinkedIn
      link: https://www.linkedin.com/in/sunghyun-chung-743139250/
    - type: ORCID
      name: ORCID
      link: https://orcid.org/0009-0006-4941-2112

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
